#     __       __   ______    ______
#     /  \     /  | /      \  /      \
#     $$  \   /$$ |/$$$$$$  |/$$$$$$  |
#     $$$  \ /$$$ |$$ |  $$/ $$ |  $$/
#     $$$$  /$$$$ |$$ |      $$ |
#     $$ $$ $$/$$ |$$ |   __ $$ |   __
#     $$ |$$$/ $$ |$$ \__/  |$$ \__/  |
#     $$ | $/  $$ |$$    $$/ $$    $$/
#     $$/      $$/  $$$$$$/   $$$$$$/
#
#     MyCraftCore paper plugin by McSwede

# /highway command to help players find nether highways
highway:
  # Enable this module
  enabled: true
  # The center coordinates for the nether highway
  center:
    x: 0
    z: 0
    y: 0
  # The dimensions of the highway
  dimensions:
    width: 0
    height: 0

# Allows players to un-strip wood by right-clicking it with and axe
unstrip:
  # Enable this module
  enabled: true

# Right-clicking someone else's pet tells you the name of the owner
petowner:
  # Enable this module
  enabled: true

# Control the speed of leaf decay
leafdecay:
  # Enable this module
  enabled: true
  # Delay in ticks to check around a broken blocks.
  # Must be at least 5
  breakDelay: 5
  # Delay in ticks to check around decaying leaves.
  decayDelay: 5
  # Break blocks one by one.
  oneByOne: false
  # Spawn particles on leaf break
  particles: true
  # Play sound on leaf break
  sound: true

# Increase the max level limit of anvils !THIS MODULE REQUIRES PROTOCOLLIB!
anvillimit:
  # Enable this module
  enabled: true
  # The new limit to use
  # Min: 41 Max: 32767 (because of a client limitation)
  limit: 32767